@TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcmlhQGdtYWlsLmNvbSIsImlhdCI6MTY2NzA2NTk2OCwiZXhwIjoxNjY3MDY5NTY4LCJzdWIiOiIxIn0.zEC0nAYddL8T1MyJea1vCDPFnvwKr1AMdmw15RKu7E8

### GET PARA VER TODOS USUÁRIOS CADASTRADOS
GET http://localhost:3000/users

### CADASTRAR USUÁRIO
POST http://localhost:3000/register
content-type: application/json

{
  "nome": "",
  "dataNascimento": "",
  "cpf": "",
  "telefone":"",
  "rua": " ",
  "bairro": "",
  "numeroCasa": "",
  "cep": "",
  "cidade": "",
  "uf": "",
  "complemento": "",
  "tipoUsuario": "",
  "email": "",
  "password": ""
}

### DELETE
DELETE http://localhost:3000/users/2

